v1.4.3 - Update Login Method and fix Login Problem with several Servers like EU
gdomenici/plugin.video.pcloud-video-streaming pull request #31
Opened 2020-10-13 16:49 UTC by lukkie112

- Update Login Method and fix Login Problem with several Servers like EU
  1. After Installation, open pCloud Settings
  2. At first Tab choose for US Server https://api.plcoud.com and for EU Server https://eapi.plcoud.com
  3. Than Enter in the correct Tab (api or eapi) your Username and Password and click OK
  4. Start pCloud and have fun
  Thx to loki1979

2020-10-14 20:54 UTC, gdomenici commented
Many thanks for the PR @lukkie112 . As soon as I have some contiguous time I'll review it properly and, if all OK, will merge. On first glance, everything looks OK though.
Kind regards,
Guido

2020-10-15 10:01 UTC, gdomenici requested changes
Please consider changing the code so that we dont store the actual creds in the config file

2020-10-15 10:01 UTC, gdomenici commented on resources/settings.xml
> +        <setting label="API PASSWORD" type="text" id="password1" default=""/>
Same comment here - I wouldnt store the username and pwd in the config file

2020-10-19 10:59 UTC, lukkie112 commented
I will ask my friend,if he can make the changes you would like

2020-10-20 09:10 UTC, gdomenici commented
> I will ask my friend,if he can make the changes you would like

Hi @lukkie112 

Thanks for that.

Another possibility (an alternative that may make your life easier) is the following:

1. You branch the code in your repo from `master` to another branch name. For example (just an example) `eapi-access-changes`.
1. you cancel this current PR.
1. then you do a _new_ PR with the existing code (no changes) from that new branch to a same-named branch in my repo.
1. then I (not you) merge that PR to that new branch in my repo.
1. then I do the necessary modifications to your code myself
1. and when I'm done I merge to my `master`.

That would make your life easier. Or, of course, you can proceed as you propose above, i.e. your friend does the necessary changes. (But even in that case, i'd recommend using a new branch name). Up to you.

Kind regards,

Guido

2021-08-04 16:40 UTC, lukkie112 commented
I was doing an new PullRequset with a new branche: Pcloud eu us login #37

So I close this one here

2021-08-04 16:40 UTC, closed without merging